FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io docker-compose && \
    usermod -aG docker jenkins

RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*

USER jenkins

