FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io docker-compose iputils-ping && \
    rm -rf /var/lib/apt/lists/* && \
    usermod -aG docker jenkins 

USER jenkins
